import type { Rollup } from 'vite';
import type { OutputBundleItem } from './cssModuleHelpers';
import { escapeRegExp } from './regexEscape';

// Output fields used when rewriting chunks in Vite's build hooks.
export type BundleChunk = Pick<Rollup.OutputChunk, 'type' | 'fileName' | 'code'> &
  Partial<Pick<Rollup.OutputChunk, 'imports' | 'modules'>>;
export type Bundle = Record<string, BundleChunk | Pick<Rollup.OutputAsset, 'type' | 'fileName'>>;
type ProxyChunk = Pick<BundleChunk, 'code' | 'fileName'>;
type ImportBinding = { imported: string; local: string };
type SystemProxyExports = {
  sharedModuleImport: string;
  exportsByName: Record<
    string,
    { type: 'helper'; code: string } | { type: 'reexport'; exportName: string }
  >;
};

export function isOutputChunk(chunk: Bundle[string]): chunk is BundleChunk {
  return chunk.type === 'chunk';
}

/**
 * Match a full variable name, including names such as $8 generated by minifiers.
 * A regex word boundary (\b) does not match a leading $. Missing that reference
 * would cause an import that is still used to be removed.
 */
export function isIdentifierReferenced(name: string, code: string): boolean {
  return new RegExp(`(?<![$\\w])${escapeRegExp(name)}(?![$\\w])`).test(code);
}

function getProxyBaseName(fileName: string): string {
  return fileName
    .replace(/^.*\//, '')
    .replace(/\.js$/, '')
    .replace(/-[A-Za-z0-9_-]+$/, '');
}

/**
 * Match `function <name>(`, escaping names that contain regex characters such as $.
 */
function functionDeclarationRegExp(name: string): RegExp {
  return new RegExp(`function\\s+${escapeRegExp(name)}\\s*\\(`);
}

function extractFunctionDeclaration(code: string, functionName: string): string | undefined {
  const functionPattern = new RegExp(
    `function\\s+${escapeRegExp(functionName)}\\s*\\([^)]*\\)\\s*\\{`
  );
  const functionStart = code.search(functionPattern);
  if (functionStart < 0) return;

  let depth = 0;
  for (let i = code.indexOf('{', functionStart); i < code.length; i++) {
    if (code[i] === '{') depth++;
    else if (code[i] === '}') {
      depth--;
      if (depth === 0) return code.slice(functionStart, i + 1);
    }
  }
}

/**
 * Choose a local name for an import that still needs its CommonJS proxy.
 * If Rollup renamed the import but its old name is still used, restore that name
 * unless another import or variable already uses it.
 */
export function resolveProxyAlias(
  binding: ImportBinding,
  originalLocalName: string,
  code: string,
  importStatement: string,
  usedLocalNames: Set<string> = new Set()
): ImportBinding {
  const codeWithoutImport = code.replace(importStatement, '');
  const isLocalNameUsed = isIdentifierReferenced(binding.local, codeWithoutImport);
  const otherImportNames = new Set<string>();
  const importRe = /import\s*\{([^}]+)\}\s*from\s*["'][^"']+["']\s*;?/g;
  let match: RegExpExecArray | null;
  while ((match = importRe.exec(codeWithoutImport)) !== null) {
    for (const spec of match[1].split(',')) {
      const parts = spec.trim().split(/\s+as\s+/);
      otherImportNames.add((parts[1] || parts[0]).trim());
    }
  }
  const canUseOriginalName =
    !isLocalNameUsed &&
    !usedLocalNames.has(originalLocalName) &&
    !otherImportNames.has(originalLocalName);
  const local = canUseOriginalName ? originalLocalName : binding.local;

  return {
    imported: binding.imported,
    local,
  };
}

export function collectLoadShareProxyChunks(
  bundle: Bundle,
  loadShareTag: string
): Map<string, ProxyChunk> {
  const proxyChunks = new Map<string, ProxyChunk>();
  for (const [fileName, chunk] of Object.entries(bundle)) {
    if (!isOutputChunk(chunk)) continue;
    if (fileName.includes(loadShareTag) && fileName.includes('commonjs-proxy')) {
      proxyChunks.set(fileName, { code: chunk.code, fileName });
    }
  }
  return proxyChunks;
}

export function collectSystemProxyExports(
  proxyChunks: Map<string, ProxyChunk>,
  loadShareTag: string
): Map<string, SystemProxyExports> {
  const systemProxyExports = new Map<string, SystemProxyExports>();

  for (const [proxyFileName, proxyInfo] of Array.from(proxyChunks.entries())) {
    const depsMatch = proxyInfo.code.match(/System\.register\(\[([\s\S]*?)\]/);
    if (!depsMatch) continue;

    const deps = Array.from(depsMatch[1].matchAll(/["']([^"']+)["']/g)).map((match) => match[1]);
    const sharedModuleImport = deps.find(
      (dep) => dep.includes(loadShareTag) && !dep.includes('commonjs-proxy')
    );
    if (!sharedModuleImport) continue;

    const sharedModuleBindings: Record<string, string> = {};
    for (const match of proxyInfo.code.matchAll(
      /([A-Za-z_$][\w$]*)\s*=\s*module\d+\.([A-Za-z_$][\w$]*)/g
    )) {
      sharedModuleBindings[match[1]] = match[2];
    }

    const exportsByName: SystemProxyExports['exportsByName'] = {};
    const objectExportMatch = proxyInfo.code.match(/exports\(\s*\{([\s\S]*?)\}\s*\)/);
    if (objectExportMatch) {
      for (const match of objectExportMatch[1].matchAll(
        /([A-Za-z_$][\w$]*)\s*:\s*([A-Za-z_$][\w$]*)/g
      )) {
        const [, exported, local] = match;
        const functionCode = extractFunctionDeclaration(proxyInfo.code, local);
        if (functionCode) exportsByName[exported] = { type: 'helper', code: functionCode };
      }
    }

    for (const match of proxyInfo.code.matchAll(/exports\(\s*["']([^"']+)["']\s*,([\s\S]*?)\);/g)) {
      const exported = match[1];
      const expression = match[2];
      // In expressions such as getAugmentedNamespace(React4), use the shared module
      // name (React4) rather than the helper when both come from the loadShare chunk.
      for (const [local, exportName] of Object.entries(sharedModuleBindings).reverse()) {
        if (isIdentifierReferenced(local, expression)) {
          exportsByName[exported] = { type: 'reexport', exportName };
          break;
        }
      }
    }

    if (Object.keys(exportsByName).length > 0) {
      systemProxyExports.set(proxyFileName, { sharedModuleImport, exportsByName });
    }
  }

  return systemProxyExports;
}

export function rewriteEsmProxyConsumers(
  code: string,
  proxyChunks: Map<string, ProxyChunk>
): string {
  let nextCode = code;
  const usedLocalNames = new Set<string>();

  for (const [proxyFileName, proxyInfo] of Array.from(proxyChunks.entries())) {
    const proxyBaseName = getProxyBaseName(proxyFileName);
    const importRe = new RegExp(
      `import\\s*\\{([^}]+)\\}\\s*from\\s*["']([^"']*${escapeRegExp(proxyBaseName)}[^"']*)["']\\s*;?`
    );
    const importMatch = importRe.exec(nextCode);
    if (!importMatch) continue;

    const importStatement = importMatch[0];
    const bindings = importMatch[1].split(',').map((specifier) => {
      const parts = specifier.trim().split(/\s+as\s+/);
      return {
        imported: parts[0].trim(),
        local: (parts[1] || parts[0]).trim(),
      };
    });

    const exportMapMatch = proxyInfo.code.match(/export\s*\{([^}]+)\}/);
    if (!exportMapMatch) continue;

    const exportsByName: Record<string, string> = {};
    for (const entry of exportMapMatch[1].split(',')) {
      const parts = entry.trim().split(/\s+as\s+/);
      if (parts.length === 2) exportsByName[parts[1].trim()] = parts[0].trim();
    }

    const inlineHelpers: Array<{ local: string; functionCode: string }> = [];
    const remainingImports: ImportBinding[] = [];
    const pendingImportNames = new Set(bindings.map((binding) => binding.local));

    for (const binding of bindings) {
      pendingImportNames.delete(binding.local);
      const originalLocalName = exportsByName[binding.imported];
      if (!originalLocalName) {
        usedLocalNames.add(binding.local);
        remainingImports.push(binding);
        continue;
      }

      const functionCode = extractFunctionDeclaration(proxyInfo.code, originalLocalName);
      if (functionCode) {
        inlineHelpers.push({
          local: binding.local,
          functionCode: functionCode.replace(
            functionDeclarationRegExp(originalLocalName),
            () => `function ${binding.local}(`
          ),
        });
        usedLocalNames.add(binding.local);
      } else {
        const unavailableLocals = new Set(usedLocalNames);
        pendingImportNames.forEach((local) => unavailableLocals.add(local));
        const resolvedBinding = resolveProxyAlias(
          binding,
          originalLocalName,
          nextCode,
          importStatement,
          unavailableLocals
        );
        usedLocalNames.add(resolvedBinding.local);
        remainingImports.push(resolvedBinding);
      }
    }

    const hasRenamedAlias = remainingImports.some(
      (binding) =>
        bindings.find((originalBinding) => originalBinding.imported === binding.imported)?.local !==
        binding.local
    );
    if (inlineHelpers.length === 0 && !hasRenamedAlias) continue;

    let replacement = '';
    if (remainingImports.length > 0) {
      const kept = remainingImports
        .map((binding) =>
          binding.imported === binding.local
            ? binding.imported
            : `${binding.imported} as ${binding.local}`
        )
        .join(',');
      replacement = `import{${kept}}from"${importMatch[2]}";`;
    }
    replacement += inlineHelpers.map((helper) => helper.functionCode).join('');

    nextCode = nextCode.replace(importStatement, () => replacement);
  }

  return nextCode;
}

export function rewriteSystemProxyConsumers(
  code: string,
  systemProxyExports: Map<string, SystemProxyExports>
): string {
  if (!code.includes('System.register(')) return code;

  let nextCode = code;
  for (const [proxyFileName, proxyInfo] of Array.from(systemProxyExports.entries())) {
    const proxyBaseName = getProxyBaseName(proxyFileName);
    const depRe = new RegExp(`["']([^"']*${escapeRegExp(proxyBaseName)}[^"']*)["']`);
    const depMatch = depRe.exec(nextCode);
    if (!depMatch) continue;

    let setterIndex = 0;
    const depListMatch = nextCode.match(/System\.register\(\[([\s\S]*?)\]/);
    if (depListMatch) {
      const deps = Array.from(depListMatch[1].matchAll(/["']([^"']+)["']/g)).map(
        (match) => match[1]
      );
      setterIndex = deps.findIndex((dep) => dep.includes(proxyBaseName));
    }
    if (setterIndex < 0) continue;

    const settersStart = nextCode.indexOf('setters: [');
    if (settersStart < 0) continue;

    const setterMatches = Array.from(
      nextCode.slice(settersStart).matchAll(/\((module\d+)\)\s*=>\s*\{([\s\S]*?)\}/g)
    );
    const setterMatch = setterMatches[setterIndex];
    if (!setterMatch) continue;

    const [fullSetter, moduleLocal, setterBody] = setterMatch;
    const helpersToInline: string[] = [];
    const nextSetterBody = setterBody.replace(
      new RegExp(`([A-Za-z_$][\\w$]*)\\s*=\\s*${moduleLocal}\\.([A-Za-z_$][\\w$]*);?`, 'g'),
      (assignment, local, imported) => {
        const mapped = proxyInfo.exportsByName[imported];
        if (!mapped) return assignment;

        if (mapped.type === 'helper') {
          helpersToInline.push(
            mapped.code.replace(functionDeclarationRegExp(imported), () => `function ${local}(`)
          );
          return '';
        }

        return `${local} = ${moduleLocal}.${mapped.exportName};`;
      }
    );

    if (nextSetterBody === setterBody && helpersToInline.length === 0) continue;

    const nextSetter = fullSetter.replace(setterBody, () => nextSetterBody);
    nextCode = nextCode.replace(fullSetter, () => nextSetter);
    nextCode = nextCode.replace(depMatch[0], JSON.stringify(proxyInfo.sharedModuleImport));
    if (helpersToInline.length > 0) {
      nextCode = nextCode.replace('execute: (function() {', () => {
        return `execute: (function() {${helpersToInline.join('')}`;
      });
    }
  }

  return nextCode;
}

export function findRemoteEntryFile(filename: string, bundle: Record<string, OutputBundleItem>) {
  // Match the remote entry's filename first. An exposed module can have the same
  // chunk name but lacks the remote entry's init/get exports. Fall back to the
  // chunk name for hashed filenames and dev server output.
  const strippedName = filename.replace(/[\[\]]/g, '_').replace(/\.[^/.]+$/, '');
  let fallback: string | undefined;
  for (const fileData of Object.values(bundle)) {
    if (fileData.fileName === filename) return fileData.fileName;
    if (
      fallback === undefined &&
      (strippedName === fileData.name || fileData.name === 'remoteEntry')
    ) {
      fallback = fileData.fileName;
    }
  }
  return fallback;
}
